### ISSUE TITLE
Group metrics by all fields except the given one

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#380] opened 2021-03-15 13:17 UTC
Issue by mahnerak:
This is especially useful when comparing experiments against seeds (when diff seeds are used for same hyperparams to ensure no variance).

**Comment by gorarakelyan** [comment] 2021-03-23 17:10
Possible duplicate of #334

**Comment by roubkar** [comment] 2021-03-28 20:48
thoughts?

<img width="475" alt="Screen Shot 2021-03-29 at 00 47 10" src="https://user-images.githubusercontent.com/9951653/112767537-4ffcef00-9028-11eb-8429-b6b2a990048b.png">

**Comment by gorarakelyan** [comment] 2021-03-29 08:19
@roubkar looks good, will test it now

**Closed** 2021-04-10 15:14 UTC
Labels: discussion, enhancement, ready-to-go
