### ISSUE TITLE
Cannot load tensorboard logs

### ISSUE THREAD

**Issue by artemisart** [aimhubio/aim#424] opened 2021-04-06 14:25 UTC
Hello, I wanted to try aim on tensorboard logs (`aim up --tf_log my_log_dir`) but it fails to load with a RecursionError in the docker logs:
```
127.0.0.1 - - [06/Apr/2021 14:14:41] "GET /api/v1/commits/tf-summary/list HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/env/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/env/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/server/app/commits/views.py", line 279, in get
    dir_paths = TFSummaryAdapter.list_log_dir_paths()
  File "/server/adapters/tf_summary_adapter.py", line 26, in list_log_dir_paths
    all_files = ls_dir([root_path])
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
...
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 32, in ls_dir
    return ls_dir(ls_head + (paths[1:] if len(paths) > 1 else []))
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 34, in ls_dir
    return [paths[0]] + (ls_dir(paths[1:]) if len(paths) > 1 else [])
  File "/server/utils.py", line 27, in ls_dir
    if len(paths) == 0:
RecursionError: maximum recursion depth exceeded in comparison
```

I tried loading the event file, the parent dir, and its parent dir, but it always fail.
Also would it be possible to import and store multiple tensorboard logs (once with something like `aim experiment import the_log_dir` then `aim up` only without a `--tf_logs`) ?

**Comment by gorarakelyan** [comment] 2021-04-06 15:37
Hi @artemisart, it appears `RecursionError` was raised because of large number of directories inside the log path. I will check it out. Thanks for reporting.

**Comment by gorarakelyan** [comment] 2021-05-13 18:53
@artemisart  the issue is resolved in the latest stable release. Please try it out and check if it works - `aim upgrade && aim up`.

**Closed** 2021-06-12 13:26 UTC
Labels: bug, ready-to-go
