### ISSUE TITLE
The metrics explorer doesn't seem to work

### ISSUE THREAD

**Issue by ilisparrow** [aimhubio/aim#2034] opened 2022-08-05 14:44 UTC
## 🐛 Bug

Hello, 
The metric explorer always says no results when I am sure it should, and It doesn't work for any metric. It doesn when I look at metrics in a run.

### To reproduce

Here are a few screenshots to show you what my problem is : 
![image](https://user-images.githubusercontent.com/4880273/183093110-93c0a7d0-dd10-480b-8aeb-c5c49b584e73.png)
When I go into a random run in the run explorer : 
![image](https://user-images.githubusercontent.com/4880273/183093320-be308fac-db8a-4a7b-a1a6-30713bc2e90f.png)

This is empty also, it used to be populated with the exact same code)
![image](https://user-images.githubusercontent.com/4880273/183101026-b5fc7816-bdcf-4d47-b4f0-c0f3f7626815.png)

### Expected behavior

Expected behavior is to get the plots displayed 

### Environment

- Aim Version 3.12.0
- Python 3.8.8
- pip 21.0.1
- Ubuntu 22.04

### Additional context

the CLI prints ; 
No index was detected

Thank you very much in advance

**Comment by roubkar** [comment] 2022-08-05 14:54
Hey @ilisparrow, thanks for reporting this, looking into it.
Meanwhile could you please share example logs to help us reproduce this 🙏

**Comment by ilisparrow** [comment] 2022-08-05 15:04
Thanks for the fast reply, 
Which logs do you me to share ? 
I track floats, integers and Text. 

I sometimes get this error  : 
```

┌------------------------------------------------------------------------┐
                Aim UI collects anonymous usage analytics.
                        Read how to opt-out here:
    https://aimstack.readthedocs.io/en/latest/community/telemetry.html
└------------------------------------------------------------------------┘
Running Aim UI on repo <Repo#2677591850585676717 path=/home/main/.aim read_only=None>
Open http://127.0.0.1:43800
Press Ctrl+C to exit
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/main/anaconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/main/anaconda3/lib/python3.8/site-packages/starlette/responses.py", line 286, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path /home/main/anaconda3/lib/python3.8/site-packages/aim_ui/build/4fca1a5251c0c653ac40.worker.js does not exist.
```

I use firefox if that's helpful

**Comment by roubkar** [comment] 2022-08-05 15:13
Hey @ilisparrow, could you share a minimal code example to reproduce the issue related to not rendering plots in Metrics Explorer?

**Comment by roubkar** [comment] 2022-08-05 16:01
Hey @ilisparrow, we've been able to reproduce the issue related to missing data in the Runs Page table and currently working on the fix.

As for not rendering the plots having a hard time reproducing it, could you try to rerun the `aim up` command and check if the issue is still there, if yes could you please share `.aim` folder (aim logs) so we can quickly debug and resolve the issue.

**Comment by ilisparrow** [comment] 2022-08-05 16:07
While I was trying to make a simpler reproducable version, I woeked as it supposed to but then came back. 

I need to force reinstall aim, and reinit the .aim rep

So I run this script as a test and it works when I run it the first time then it doesn't anymore. 
```

from aim import Run


run = Run(
    experiment="ocr_orientation",
)

run["hparams"] = {
    "framework": "mmocr",
    "backbone_det": "param",
    "bbone_rec": "secondBB",
}


for i in range(10):
    run.track(
        i,
        name="well oriented from confidence",
    )
    run.track(
        1,
        name="AAAAA",
    )

```

**Comment by ilisparrow** [comment] 2022-08-05 16:08
great ! thanks, for some reason, even when reinstall it and reset the .aim folder, It keeps in cache the old params, why is that ?

**Comment by roubkar** [comment] 2022-08-05 16:12
How did you reset `.aim` folder, have you run `aim init` command?

**Comment by ilisparrow** [comment] 2022-08-05 16:19
So : 
reinstall-> aim up : doesn't work
reinstall-> aim init ->1 run -> aim up : doesn't work
rm .aim-> aim init ->1 run -> aim up : doesn't work



So I can't figure out how does the bug happen.
Here is the .aim folder : 
[aim.zip](https://github.com/aimhubio/aim/files/9270223/aim.zip)

**Comment by ilisparrow** [comment] 2022-08-05 16:20
> How did you reset `.aim` folder, have you run `aim init` command?

I deleted it and just did aim init.

For some reason I feel like this bug is related to the fact that I still get the chips of the old params when I delete the folder and init it again

**Comment by ilisparrow** [comment] 2022-08-05 16:22
Aha ! 
 reinstall-> rm .aim ->aim init ->1 run -> aim up :  works

**Comment by mihran113** [comment] 2022-08-05 16:39
hey @ilisparrow. I was able to use metrics explorer successfully on the logs that you've provided. The fact that you're still getting the old params after resetting the `.aim` directory is pretty strange, and my guess here is that browser keeps some kind of cache actually. Could you try to clear the browser cache and see if that helps somehow?

**Comment by ilisparrow** [comment] 2022-08-05 16:49
Thanks ! 
So it works on chrome/localhost and firefox/localhost and chrome/127.0.0.1 but not on firefox/127.0.0.1 
![image](https://user-images.githubusercontent.com/4880273/183123565-a8e35a5a-8118-41b0-b072-68aacbaab508.png)
![image](https://user-images.githubusercontent.com/4880273/183123796-8d11d1d4-9c3c-4a7d-b74f-0df48c1c6a7e.png)

You need to come back to the page for the new request to be generated.

I guess, that's already a win.

**Comment by mihran113** [comment] 2022-08-05 17:11
@ilisparrow Pretty strange, I'm using firefox as well but on macOS, and it seems to be working fine in any case, will investigate further to see if can do anything to avoid it on ubuntu as well, meanwhile glad that there's some workaround. Please keep the issue open for the runs dashboard values rendering as that's a genuine issue on our side, and there's a work in progress already for the fix.

**Comment by ilisparrow** [comment] 2022-08-05 17:43
No problem, I am glad I "contributed" a bit :). 
Thanks for being this quick !

**Comment by roubkar** [comment] 2022-08-05 20:25
Hey @ilisparrow, we have just released v3.12.2 where the issue with Runs Page table values rendering is resolved.
To upgrade please run `pip install aim --upgrade`

**Comment by ilisparrow** [comment] 2022-08-06 00:10
Thanks, that was fast ! I did some more testing, and the problem seems to definitely be a firefox problem. I can't get the metrics explorer to display consistently in ff but in chrome I do.

Thanks again :)

**Comment by gorarakelyan** [comment] 2022-08-17 10:15
closing this issue, as the fix was shipped with v3.12.2. @roubkar could you please submit a separate issue wrt firefox support to track the progress there.

**Closed by gorarakelyan** 2022-08-17 10:15 UTC
Labels: type / bug, help wanted, area / Web-UI, phase / shipped

**Comment by roubkar** [comment] 2022-08-17 10:17
> closing this issue, as the fix was shipped with v3.12.2. @roubkar could you please submit a separate issue wrt firefox support to track the progress there.

Sure!

**Comment by gloryVine** [comment] 2022-08-25 18:21
I think this has to be reopened.
I am currently running a model with a simple ```run.track(reward, name='reward', epoch=n)``` and am getting an empty Metrics Explorer when running the model with **Python 3.9, aim 3.13.0```, but the run is tracked correctly when changing to an environment with **Python 3.8, aim 3.10.3```. This isn't Firefox either, I tried with both Chromium and Safari.

**Comment by mihran113** [comment] 2022-08-26 09:44
Hey @gloryVine! Thanks for the report. Can I ask you to provide a little bit more information about the case that is failing? (i.e. the exact python version, OS version, and if possible an example script to reproduce the issue.)
