### ISSUE TITLE
Ability to archive a run from Explore

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#449] opened 2021-04-21 12:05 UTC
Feature Request by Hrant Khachatrian on Slack

Add ability to archive a run from the Explore screen.

**Comment by roubkar** [comment] 2021-04-22 06:49
What if we add an ability to archive all hidden metrics?

![Screen Shot 2021-04-22 at 10 48 34](https://user-images.githubusercontent.com/9951653/115668567-4d0bca80-a358-11eb-8258-73d802f526b0.png)

**Comment by roubkar** [comment] 2022-03-20 21:03
Duplicate of https://github.com/aimhubio/aim/issues/1185

**Closed by roubkar** 2022-03-20 21:03 UTC
Labels: duplicate, type / enhancement
