### ISSUE TITLE
Issue when using PyTorch Lightning integration while logging epochs

### ISSUE THREAD

**Issue by dennisbappert** [aimhubio/aim#1359] opened 2022-02-17 13:37 UTC
## 🐛 Bug

aim fails to track the epoch metric produced by PyTorch Lightning:

```
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 242, in advance
    self.trainer.logger_connector.update_train_epoch_metrics()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 232, in update_train_epoch_metrics
    self.log_metrics(self.metrics["log"])
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 121, in log_metrics
    self.trainer.logger.save()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/loggers/base.py", line 427, in save
    logger.save()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/loggers/base.py", line 317, in save
    self._finalize_agg_metrics()
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/loggers/base.py", line 152, in _finalize_agg_metrics
    self.log_metrics(metrics=metrics_to_log, step=agg_step)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/dbpprt/dev/lama/src/utils/aim_logger.py", line 76, in log_metrics
    self.experiment.track(v, name=name, context=context)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/aim/sdk/run.py", line 412, in track
    self._track_impl(value, track_time, name, step, epoch, context=context)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/aim/sdk/run.py", line 443, in _track_impl
    self._update_sequence_info(seq_info, ctx, val, name, step)
  File "/home/dbpprt/miniforge3/envs/lama/lib/python3.9/site-packages/aim/sdk/run.py", line 686, in _update_sequence_info
    raise ValueError(f'Cannot log value \'{val}\' on sequence \'{name}\'. Incompatible data types.')
ValueError: Cannot log value '4' on sequence 'epoch'. Incompatible data types.
```

PL Trainer Config is set to:

```yaml
check_val_every_n_epoch: 5
```

### Expected behavior

No crash.

### Environment

- Aim Version 3.5.3
- Python version 3.9
- OS: Ubuntu

**Comment by alberttorosyan** [comment] 2022-02-17 14:00
Hi @dennisbappert ! Thanks for reporting the issue.
From the error message you have shared I can assume that for the same metric `'epoch'` values with different types had been logged. This is something `aim` does not allow to do.
I would like to help with this and understand the root cause of such case happening. Would you mind to share a minimal test-case?

**Comment by dennisbappert** [comment] 2022-02-17 14:00
Seems to be a bug in PyTorch Lightning, with check_val_every_n_epoch. The last train epoch has reports epoch as int but all previous epochs are reported as floats.

![image](https://user-images.githubusercontent.com/7000188/154497051-5672d681-1205-4427-8880-b52957c32619.png)

**Comment by dennisbappert** [comment] 2022-02-17 14:24
![image](https://user-images.githubusercontent.com/7000188/154501402-a8643100-9d01-4ef1-82c0-177b6dfbf3cf.png)

Did that for now, I will investigate though where that type change originates from.

**Comment by alberttorosyan** [comment] 2022-02-20 18:51
@dennisbappert should we consider the issue not related to `aim`? If there is an issue opened on PyTorch Lightning, we can mention it here and close this issue.

**Comment by dennisbappert** [comment] 2022-02-22 10:51
I will open an issue in PL and reference this one.

**Comment by dennisbappert** [comment] 2022-02-22 18:58
Tracked [here]

(https://github.com/PyTorchLightning/pytorch-lightning/issues/12050) #https://github.com/PyTorchLightning/pytorch-lightning/issues/12050

**Comment by gorarakelyan** [comment] 2022-06-09 19:13
closing this issue as it is not related to Aim

**Closed by gorarakelyan** 2022-06-09 19:13 UTC
Labels: type / bug, help wanted, phase / exploring, area / SDK-storage
