### ISSUE TITLE
`aim up`: disable corrupted runs caused by `rsync`

### ISSUE THREAD

**Issue by twni2016** [aimhubio/aim#2274] opened 2022-10-12 16:54 UTC
## 🚀 Feature

In `aim up`, disable the query / visualization of the unfinished runs that are corrupted. 

### Motivation

When `rsync` the `.aim` folder from a remote server into a local machine, unfinished runs are very likely to be corrupted, so they cannot be queried in `aim up`. This causes the `aim up` to fail to launch, without showing any existing runs that are already finished.

**Comment by twni2016** [comment] 2022-10-13 17:21
A follow-up feature request: could we preserve the `active` status of existing runs after `rsync` new runs? Now all the previous archived runs become active after `rsync`.

**Comment by gorarakelyan** [comment] 2022-10-16 19:27
hm weird.. @alberttorosyan are run props (such as active) stored in run containers or in sqlite db? might it be because of failing to sync sqlite db?

**Comment by alberttorosyan** [comment] 2022-10-18 06:44
@gorarakelyan as the runs properties are stored in sqlite db, the changes on a destination side of `rsync` are overwritten. This can be resolved by skipping `.aim/run_metadata.sqlite`, however, the other changes, such as new runs information will not be synced.
The root cause of the issue is that `.aim` repos are not supposed to be synced in this way.

@twni2016, as I understand, accessing Aim UI when `aim up` runs on remote is not possible. What about using SSH port forwarding instead?

**Comment by twni2016** [comment] 2022-10-26 19:21
@alberttorosyan Yes, I can use ssh forwarding now. Thank you for your suggestion! 

But the corrupted runs still exist in the source `.aim` repo, e.g. `aim.sdk.errors.RepoIntegrityError: Missing props for Run` though they seem not to affect `aim up`.

**Comment by twni2016** [comment] 2022-11-04 06:35
This issue is not important to me now, as I switch to ssh forwarding to view aim application. Feel free to close this issue.

**Comment by gorarakelyan** [comment] 2022-11-04 17:53
@twni2016 sorry for a late reply. Glad there are no issues now.

**Closed by gorarakelyan** 2022-11-04 17:53 UTC
Labels: type / enhancement, phase / exploring, area / SDK-storage
