### ISSUE TITLE
Performance issues when viewing images by selecting the images tab of run in aim ui

### ISSUE THREAD

**Issue by Dong-Ki-Lee** [aimhubio/aim#2424] opened 2022-12-12 04:24 UTC
## 🐛 Bug

After saving the image over several steps, if I try to check it in the aim ui, there will be a part that stops or becomes very slow while loading the image.

In the above situation (slow or frozen), all other requests are not received regardless of the number of workers.

### To reproduce
After saving the images on the remote server with the code below, the issue occurs when reading the image on the run page.

change [aim ip] and [model-path] in the code below
check this repo https://github.com/huggingface/diffusers
i tested with stable diffusion 2.0 model

```
import argparse
import hashlib
import itertools
import math
import os
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
import torch.utils.checkpoint
from torch.utils.data import Dataset

from accelerate import Accelerator
from accelerate.logging import get_logger
from accelerate.utils import set_seed
from diffusers import AutoencoderKL, DDPMScheduler, StableDiffusionPipeline, UNet2DConditionModel, StableDiffusionImg2ImgPipeline
from diffusers.optimization import get_scheduler
from huggingface_hub import HfFolder, Repository, whoami
from PIL import Image
from torchvision import transforms
from tqdm.auto import tqdm
from transformers import AutoTokenizer, PretrainedConfig
from aim import Run, Image
import aim


logger = get_logger(__name__)
aim_run = Run(repo='[aim ip]', experiment='test', log_system_params=True)
aim_run.name = 'test'

save_path = '[model-path]'

p = StableDiffusionPipeline.from_pretrained(save_path, torch_dtype=torch.float16, revision='fp16').to('cuda')

prompt = [
    "test",
    "test",
    "test",
    "test",
    "test",
    "test",
    "test",
    "test",
    "test",
    "test",
    "test",
]

num_inference_steps = 25
guidance_scale = 9.0
num_samples = 5

for i in range(len(prompt)):
    images = p(
        prompt[i],
        num_images_per_prompt=num_samples, 
        num_inference_steps=num_inference_steps, 
        guidance_scale=guidance_scale,
    ).images

    aim_images = []
    
    for j in range(len(images)):
        aim_images.append(aim.Image(images[j], caption=f'{prompt[i]} examples'))
        
    aim_run.track(value=aim_images, name='generated images', step=i)
```

### Expected behavior

The image should be loaded and displayed without slowing down or stopping.

Also, even if the image stops while loading, the server should not stop so that other requests can be received.

### Environment

- Aim Version 3.15.0
- Python version 3.10
- pip version 22.3.1
- OS (e.g., Linux) amazonlinux2 arm
- arm cpu (graviton3, c7g)
- remote server setting
- test in chrome, safari.. Probably not a browser issue.

### Additional context

When storing many images (for example, when learning by 30000 steps, 10-20 image results are saved for every 1000 steps)
When I move to the image page of the run, the images displayed on the top (ex. step 30000, 29000, 28000 step images are visible on the page at once, up to 27000 and 26000 step images are not visible on the page, but are loaded at once and scroll down It looks good right away.) It loads and looks good, but if I scroll below it, it takes a very long time to load from 25000 and 24000 step images.

In this state, the server does not receive any requests after that, and even if I connect from another browser, I cannot connect.
However, it seems to be piled up in the queue, and the work of reading the image is very slow, but when it is finished, requests that have been delayed since then are processed at once.

The following is the log that appears in the situation described above when the server is started in the debug logging state.

Cannot index Run 8c924d585f164800b74169e7. Index is locked.
Cannot index Run 8c924d585f164800b74169e7. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
Cannot index Run 2a38ac7512a54484b028fab0. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
INFO: [IP]:58789 - "POST /runs/images/get-batch HTTP/1.1" 200 OK
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.
Cannot index Run efe94f87aa774888b4854a33. Index is locked.
Cannot index Run efe94f87aa774888b4854a33. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.
INFO: [IP]:58567 - "POST /runs/images/get-batch HTTP/1.1" 200 OK
Cannot index Run 5150187ef9534463aeb0b17b. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.
Cannot index Run 8c1e7409ee414dda8f195e1e. Index is locked.

**Comment by roubkar** [comment] 2022-12-12 07:27
Hey @Dong-Ki-Lee, thanks a lot for sharing the details, we have received reports like this earlier and are currently exploring possible solutions to fix this. We'll keep you updated on the progress.

**Comment by roubkar** [comment] 2022-12-12 07:34
Related to https://github.com/aimhubio/aim/issues/2180

**Comment by alberttorosyan** [comment] 2022-12-12 09:59
@Dong-Ki-Lee regarding the warning messages:
```
Cannot index Run 8c924d585f164800b74169e7. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
Cannot index Run 32dff8c6567b4eb782501460. Index is locked.
```

May I ask you to upgrade to the latest `3.15.1` version? There was a patch released, fixing these.

**Comment by Dong-Ki-Lee** [comment] 2022-12-12 15:36
Hello @alberttorosyan 

As you said, the error log does not occur after updating to 3.15.1. :)

**Comment by Dong-Ki-Lee** [comment] 2022-12-12 15:39
If possible, could you shed some light on why (and if the problem has been identified) there is a bug that causes the aim ui to freeze when reading images?

**Comment by Dong-Ki-Lee** [comment] 2023-01-02 06:00
hello @roubkar, Could you please answer the above questions? (Q. If possible (and if the problem is identified), can you hear some reasons why aim ui is having a bug when reading images? )

**Comment by roubkar** [comment] 2023-01-03 06:54
Hey @Dong-Ki-Lee, unfortunately, we haven’t been able to reproduce this issue. We're still exploring to find the cause. Also, we're working on a new base for explorers, enabling many performance optimizations. And we're planning to move all the existing explorers to the new base in the upcoming milestones.

**Comment by Dong-Ki-Lee** [comment] 2023-01-03 07:04
@roubkar Thank you for your answer.
I have a few additional questions.
1. Is there anything I can do to check the problem? (For example, creating and sharing a problematic environment, sharing the conditions of the problematic environment in more detail, or logging in a specific part of the environment. and so on)
2. Is "new base" a different repository? (e.g., aimstack.io) 
3. Regarding number 2, if it is to move to another repository, will there be a change in the license?

**Comment by roubkar** [comment] 2023-01-03 07:55
> @roubkar Thank you for your answer. I have a few additional questions.
> 
> 1. Is there anything I can do to check the problem? (For example, creating and sharing a problematic environment, sharing the conditions of the problematic environment in more detail, or logging in a specific part of the environment. and so on)
> 2. Is "new base" a different repository? (e.g., aimstack.io)
> 3. Regarding number 2, if it is to move to another repository, will there be a change in the license?

re 1: That would be awesome 🙏 
re 2,3: it's under the same repo (same license), `Figures` and `Audios` explorers are built on top of that new base.

**Comment by hadim** [comment] 2023-01-28 12:58
I am also seeing the same issue. Is there is anything we can do to manually remove the lock from the index without corrupting the database?

**Comment by hadim** [comment] 2023-01-28 13:28
It was creating a massive slowdown of the UI and the server (with a very disk I/O and CPU usage).

The only way to get back to normal was to delete `.aim/locks/index.softlock`. Fortunately, it didn't corrupt the run that was locked.

**Comment by alberttorosyan** [comment] 2023-01-30 07:37
> It was creating a massive slowdown of the UI and the server (with a very disk I/O and CPU usage).
> 
> The only way to get back to normal was to delete `.aim/locks/index.softlock`. Fortunately, it didn't corrupt the run that was locked.

@hadim, are you using the latest stable version of Aim? With Aim 3.15+ the locking and runs indexing mechanism has been completely changed and the lock for index is controlled only by the `aim up` command. You should stop all runs with the older versions, make sure the `.aim/locks/index.softlock` is not left (deleting it manually is OK as far as there are no runs in progress), then start runs with the new version.

**Comment by hadim** [comment] 2023-01-30 14:13
Thanks for the details. We are only using the latest stable versions 3.15.2. All runs were already stopped. Good to hear removing the soft lock file is ok.

**Comment by roubkar** [comment] 2023-04-06 18:43
Hey everyone 👋 the fix for this issue has been released with v3.17.3
To upgrade please run `pip install aim --upgrade`

@asynclee thanks for your contribution 🙌

**Comment by roubkar** [comment] 2023-05-02 07:09
Hey @asynclee, could you confirm that this issue is resolved?

**Comment by asynclee** [comment] 2023-05-02 07:12
@roubkar I confirmed that the issue has been resolved. Is there still an issue?

**Comment by roubkar** [comment] 2023-05-02 07:34
> @roubkar I confirmed that the issue has been resolved. Is there still an issue?

Thanks, just wanted to make sure before closing this 🙂

**Closed by roubkar** 2023-05-02 07:34 UTC
Labels: type / bug, help wanted, area / Web-UI, phase / shipped, type / poor-performance
