### ISSUE TITLE
Img load failure when AIM_UI_BASE_PATH is changed

### ISSUE THREAD

**Issue by ptaejoon** [aimhubio/aim#1332] opened 2022-02-15 08:50 UTC
## 🐛 Bug

https://github.com/aimhubio/aim/blob/main/aim/web/configs.py#L8
Changing AIM_UI_BASE_PATH causes failure on loading imgs.
loading imgs below :
/static-files/static/media/experiments.d7187189.svg
/static-files/static/media/runs.eaf7976b.svg
returned 404 error

### To reproduce

1. aim up after set AIM_UI_BASE_PATH to another name (ex. aim up --base-path="1234")
2. visit web-ui (ex. visit <aim-web-url>/1234)
3. check web-console (there will be error-msgs with 404)

### Expected behavior
There should be no failure on loading imgs

### Environment

- Aim Version : 3.5
- Python version : 3.8
- pip version
- OS (e.g., Linux) : Mac
- Any other relevant information

### Additional context

This is when base-url is changed
<img width="224" alt="스크린샷 2022-02-15 오후 5 29 59" src="https://user-images.githubusercontent.com/17878758/154025477-a5f58414-e1ca-461b-a53c-f0ef9b82da83.png">

This is when base-url is set to default
<img width="235" alt="스크린샷 2022-02-15 오후 5 32 31" src="https://user-images.githubusercontent.com/17878758/154025514-0166de53-7751-4c6e-a77c-38acd556996c.png">

this issue came from below:
https://aimstack.slack.com/archives/C02V1DJV2BH/p1644914072221839

**Comment by alberttorosyan** [comment] 2022-02-15 10:16
Thanks @ptaejoon for raising the issue!
@Hamik25 could you please share additional context regarding this issue? Lets also explore possible approaches to fix.

**Comment by Hamik25** [comment] 2022-02-17 09:46
The issue is related with import SVG files from CSS files during loading SVG files our CSS loader doesn't know about the base path and the base path is not included in GET request URL for these SVG files at the same time static server return 404 because it knows about the base path and serves only request under the base path.

**Comment by roubkar** [comment] 2023-03-14 09:56
Closing this issue as the Home page was redesigned.

**Closed by roubkar** 2023-03-14 09:56 UTC
Labels: type / bug, help wanted, area / Web-UI
