### ISSUE TITLE
Add scatterplot and scatterplot comparison features

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#388] opened 2021-03-15 13:46 UTC
Issue by Denovo folks:
When comparing metrics to metrics, scatterplots offer a great way to put them into perspective.
For certain RL cases, it would also helpful to be able to compare different scatterplots from different episodes.

**Comment by gorarakelyan** [comment] 2021-10-29 18:13
Duplicate of #491

**Closed by gorarakelyan** 2021-10-29 18:13 UTC
Labels: type / enhancement, phase / exploring
