### ISSUE TITLE
remote server repo.query_metrics() raises AttributeError: 'NoneType' object has no attribute 'caches'

### ISSUE THREAD

**Issue by YodaEmbedding** [aimhubio/aim#1972] opened 2022-07-18 19:10 UTC
## 🐛 Bug

`Repo.query_metrics` for an aim server repo raises:

```python
AttributeError: 'NoneType' object has no attribute 'caches'
```

### To reproduce

```python
import aim

# Choose one:
repo_path = "/path/to/aim/repo"      # Good.
repo_path = "aim://localhost:53666"  # Bad.

repo = aim.Repo(repo_path)  # , read_only=True)
query = "run.model.name == 'example-model'"

runs = list(repo.iter_runs())  # This works.
runs = list(repo.query_metrics(query).iter_runs())
runs = list(repo.query_runs(query).iter_runs())
```

Side note: I'm not sure what the difference between `query_metrics` and `query_runs` is.

### Expected behavior

No AttributeError.

### Environment

- Aim Version: 3.11.1
- Python version: 3.8.10
- pip version: 22.0.4
- OS: Linux

**Comment by gorarakelyan** [comment] 2022-07-22 18:44
@YodaEmbedding the issue was fixed and shipped with Aim v3.12.0!

**Comment by YodaEmbedding** [comment] 2022-07-27 23:47
Related issue:

```python
context = Context({"loader": "valid", "scope": "epoch"})
run.get_metric("loss", context)
```

Gives:

```
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    metric = run.get_metric(min_metric, context)
  File "/site-packages/aim/sdk/run.py", line 511, in get_metric
    if self.check_metrics_version():
  File "/site-packages/aim/sdk/base_run.py", line 64, in check_metrics_version
    traces_tree = self.meta_run_tree.get('traces', {})
  File "aim/storage/treeview.py", line 59, in aim.storage.treeview.TreeView.get
  File "aim/storage/treeview.py", line 51, in aim.storage.treeview.TreeView.__getitem__
  File "aim/storage/treeview.py", line 39, in aim.storage.treeview.TreeView.collect
  File "/site-packages/aim/storage/treeviewproxy.py", line 196, in collect
    return self.tree.collect(self.absolute_path(path), strict, resolve_objects)
  File "/site-packages/aim/storage/treeviewproxy.py", line 76, in collect
    return self._rpc_client.run_instruction(self._hash, self._handler, 'collect', (path, strict, resolve_objects))
  File "/site-packages/aim/ext/transport/client.py", line 109, in run_instruction
    return self._run_read_instructions(queue_id, resource, method, args)
  File "/site-packages/aim/ext/transport/client.py", line 134, in _run_read_instructions
    return decode_tree(unpack_stream(resp))
  File "aim/storage/treeutils.pyx", line 270, in aim.storage.treeutils.decode_tree
  File "aim/storage/treeutils.pyx", line 95, in aim.storage.treeutils.fold_tree
  File "aim/storage/treeutils.pyx", line 126, in iter_fold_tree
  File "aim/storage/treeutils.pyx", line 201, in aim.storage.treeutils.DecodePathsVals.__next__
  File "aim/storage/treeutils.pyx", line 214, in aim.storage.treeutils.DecodePathsVals._next
  File "/site-packages/aim/ext/transport/message_utils.py", line 58, in unpack_stream
    for msg in stream:
  File "/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/site-packages/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating responses: Object of type bytes is not JSON serializable"
        debug_error_string = "{"created":"@1658965367.110473000","description":"Error received from peer ipv4:10.1.16.15:53666","file":"src/core/lib/surface/call.cc","file_line":1064,"grpc_message":"Exception iterating responses: Object of type bytes is not JSON serializable","grpc_status":2}"
>
```

**Comment by mihran113** [comment] 2022-07-28 10:55
hey @YodaEmbedding! Thanks for the report, this one seems to be working fine on my end, could you please provide the version of aim you are using? (both for client and server sides)

**Comment by YodaEmbedding** [comment] 2022-07-28 18:29
v3.12.0 for both.

Server:
```bash
λ aim version
Aim v3.12.0
λ aim server
The lock file /path/to/aim/repo/.aim/.repo_lock is on a filesystem of type `wekafs` (device id: ...). Using soft file locks to avoid potential data corruption.
Running Aim Server on repo `<Repo#4923689016395883677 path=/path/to/aim/repo/.aim read_only=None>`
Server is mounted on 0.0.0.0:53800
Press Ctrl+C to exit
```

Client:
```bash
λ aim version
Aim v3.12.0
λ python test.py
```

**Comment by mihran113** [comment] 2022-07-28 19:48
Let me know if I can provide any help. If possible, you also can share some example logs and script, so I can reproduce the case exactly on my side.

**Comment by gorarakelyan** [comment] 2022-08-17 10:19
Closing the issue as the main bug was resolved. @YodaEmbedding could you please submit a separate issue (if it still appears) to track its progress there.

**Closed by gorarakelyan** 2022-08-17 10:19 UTC
Labels: type / bug, help wanted, phase / shipped
