### ISSUE TITLE
Ability to apply grouping to specific metrics.

### ISSUE THREAD

**Issue by Khazhak** [aimhubio/aim#452] opened 2021-04-23 15:50 UTC
**Problem**
Let's suppose I have 3 metrics: "loss", "another_loss" and "accuracy". I want to be able to see "loss" and "another_loss" displayed in one chart, but the "accuracy" on another.

**Comment by gorarakelyan** [comment] 2021-10-29 18:28
Duplicate of #347

**Closed by gorarakelyan** 2021-10-29 18:28 UTC
Labels: type / enhancement
