### ISSUE TITLE
Bug for infinite value

### ISSUE THREAD

**Issue by IcarusWizard** [aimhubio/aim#330] opened 2021-03-06 07:36 UTC
Hi. I am experimenting with some RL algorithms, and sometimes I will record some values like `inf` into logs due to the unstableness of the algorithms. However, it seems like that aim does not work with these values. When `inf` was recorded, the experiment will still be shown on the dashboard, but when clicking in, it shows "Experiment does not exist".

**Comment by gorarakelyan** [comment] 2021-03-06 09:20
Hi @IcarusWizard ,

Thanks for reporting, I will look into it asap.

Also could you please share your thoughts on how to visualize inf values?
Currently Aim skips infs, but probably there is a better approach. Thanks.

**Comment by IcarusWizard** [comment] 2021-03-06 09:44
Thanks for the quick reply. As far as I know, in tensorboard, values like `inf` and `nan` are represented by a triangle on the plot. While in matplotlib, these values are just skipped and leaving a blank space on the plot. I think either of these approaches is ok.

**Comment by gorarakelyan** [comment] 2021-03-06 10:39
Great, makes a lot of sense. Thanks for the details.

**Comment by gorarakelyan** [comment] 2021-03-16 12:04
@IcarusWizard I tested tracking inf values, surprisingly it works fine for me.
Is it possible for you to share your logs so I could troubleshoot the issue? Thanks!

**Comment by IcarusWizard** [comment] 2021-03-16 16:30
Hope this helps. https://drive.google.com/file/d/1IJBXlfuCDHQaeWQHxbUvBplSFQSfIrvc/view?usp=sharing

**Comment by gorarakelyan** [comment] 2021-03-17 08:53
Thanks a lot!

**Comment by gorarakelyan** [comment] 2021-04-12 13:03
@IcarusWizard the issue is resolved in the latest stable release. Please try it out and check if it works - `aim upgrade && aim up`.
Inf values are just skipped now, but their [visualization](https://github.com/aimhubio/aim/issues/435) is already included in the upcoming release [milestone](https://github.com/aimhubio/aim/milestone/6).
We also noticed an issue regarding to plotting big float values(e.g. 10e16 and greater), it will be included in the next release as well.

**Closed** 2021-04-12 16:52 UTC
Labels: bug, ready-to-go

**Comment by IcarusWizard** [comment] 2021-04-12 16:53
Thanks for the update! The experiments are now correctly displayed.
